import aiAbstractionLayer from './abstraction.js';
import analyticsService from '../analytics/service.js';
import projectService from '../projects/service.js';
import Task from '../tasks/model.js';
import logger from '../../utils/logger.js';

/**
 * AI SERVICE MODULE - SERVICE LAYER (service.js)
 * Responsibility: Implements core AI cognitive capabilities:
 *   1. Sprint summary analytics synthesis.
 *   2. Dynamic project deadline risk profiling.
 *   3. Intelligent developer workloads balance predictions.
 *   4. Generative text sections for administrative executive reporting.
 */
class AiService {

  /**
   * Generates a comprehensive summary of a project's sprint metrics
   */
  async generateSprintSummary(projectId, organizationId) {
    // 1. Gather live project analytics
    const project = await projectService.getProjectById(projectId, organizationId);
    const analytics = await analyticsService.getProjectAnalytics(projectId, organizationId);

    const completionRate = analytics.taskMetrics.total > 0 ? Math.round((analytics.taskMetrics.completed / analytics.taskMetrics.total) * 100) : 0;
    
    // 2. Draft target AI Prompt
    const systemInstruction = 'You are the TaskFlow Principal Scrum Master and Scrum Coach.';
    const prompt = `
      Analyze the sprint performance metrics for Project "${project.name}" (Code: ${project.code}):
      - Total Tasks: ${analytics.taskMetrics.total}
      - Completed Tasks: ${analytics.taskMetrics.completed}
      - Milestones Achieved: ${analytics.milestoneMetrics.achieved}/${analytics.milestoneMetrics.total}
      - Completion Rate: ${completionRate}%
      - Current Project Health Score: ${project.healthScore}/100

      Draft a professional sprint review summary structured in markdown, highlighting:
      1. Overall Accomplishments & Progress.
      2. Development Velocity Assessment.
      3. Key Blockers & Risks discovered.
      4. Targeted actionable recommendations for the next sprint.
    `;

    // 3. Request generative text or fallback
    const aiText = await aiAbstractionLayer.generateText(prompt, systemInstruction);
    if (aiText) return aiText;

    // Premium Local Fallback Synthesis
    logger.debug('[TaskFlow AI]: Resolving Local Sprint Summary Engine Fallback...');
    const accomplishments = completionRate >= 80 
      ? `Outstanding progress! The team has cleared **${analytics.taskMetrics.completed} out of ${analytics.taskMetrics.total}** tasks, securing an elite **${completionRate}%** completion rate.`
      : completionRate >= 50
      ? `Sensible progress. The team achieved a **${completionRate}%** completion rate, but multiple tasks remain pending in backlog columns.`
      : `Critical sprint delay. Completion rate is sitting at a low **${completionRate}%**. Urgent administrative alignment is required.`;

    return `### 🏃 Sprint Review Summary: ${project.name} (${project.code})
*Generated by TaskFlow Analytics AI Engine*

#### 1. Accomplishments & Progress
${accomplishments} Currently tracking **${analytics.milestoneMetrics.total - analytics.milestoneMetrics.achieved}** pending milestones.

#### 2. Development Velocity Assessment
The sprint velocity is tracking at **${completionRate}%** efficiency. The project health index remains rated at **${project.healthScore}/100** based on approaching target dates.

#### 3. Key Blockers & Risks
- **Overdue Workloads**: Stale tasks are threatening upcoming milestones due dates.
- **Resource Constraints**: High concentration of critical tasks assigned to single developers.

#### 4. Targeted Actionable Recommendations
1. **Clear Blocked Pipelines**: Hold an immediate daily standup focused specifically on clearing BLOCKED columns.
2. **Reallocate Workload**: Shift pending tasks from overallocated team leads to available junior developers.
3. **Refine Scope Limits**: Reduce the incoming sprint backlog size by 15% to match actual development velocity.
`;
  }

  /**
   * Assesses deadline risk factors for a project
   */
  async assessDeadlineRisk(projectId, organizationId) {
    const project = await projectService.getProjectById(projectId, organizationId);
    
    // Get incomplete tasks past or near deadline
    const [overdueCount, totalTasks] = await Promise.all([
      Task.countDocuments({ projectId, organizationId, status: { $ne: 'COMPLETED' }, endDate: { $lt: new Date() } }),
      Task.countDocuments({ projectId, organizationId })
    ]);

    const systemInstruction = 'You are the TaskFlow Risk Compliance Officer.';
    const prompt = `
      Assess the project deadline risks for Project "${project.name}" (Code: ${project.code}):
      - Total Tasks: ${totalTasks}
      - Overdue Incomplete Tasks: ${overdueCount}
      - Project Health Index: ${project.healthScore}/100
      - Project End Target Date: ${project.endDate ? project.endDate.toISOString().split('T')[0] : 'Not set'}

      Evaluate the deadline risks and provide a clear assessment in markdown covering:
      1. Concrete Risk Level rating (LOW, MEDIUM, HIGH).
      2. Analysis of core risk triggers.
      3. Practical, strategic risk mitigation actions.
    `;

    const aiText = await aiAbstractionLayer.generateText(prompt, systemInstruction);
    if (aiText) return aiText;

    // Premium Local Fallback Risk Assessment
    logger.debug('[TaskFlow AI]: Resolving Local Deadline Risk Engine Fallback...');
    const riskLevel = overdueCount > 3 || project.healthScore < 60 ? 'HIGH' : overdueCount > 0 ? 'MEDIUM' : 'LOW';
    const riskColor = riskLevel === 'HIGH' ? '🔴' : riskLevel === 'MEDIUM' ? '🟡' : '🟢';

    return `### ⚠️ Project Deadline Risk Assessment: ${project.name}
*Generated by TaskFlow Risk Assessment AI Engine*

#### 1. Risk Level Profile: ${riskColor} **${riskLevel} RISK**
- **Overdue Tasks Count**: ${overdueCount} incomplete tasks are currently past their due dates.
- **Project Health Score**: Sitting at **${project.healthScore}/100**.

#### 2. Core Risk Triggers
- ${overdueCount > 0 ? `**Delayed Commitments**: ${overdueCount} critical tasks have breached their target deadlines without status completion.` : '**Active Pipeline**: All active tasks remain within scheduled deadline bounds.'}
- **Milestone Exposure**: Approaching project milestones are highly dependent on overdue subtasks.

#### 3. Strategic Mitigation Actions
1. **Freeze Scope Creep**: Block any additional feature requests or task additions to the current phase immediately.
2. **Crash the Schedule**: Temporarily allocate secondary developers to pair-program and clear overdue bottlenecks.
3. **Negotiate Extensions**: Proactively communicate timeline exposure risks to stakeholders and secure a 2-week buffer.
`;
  }

  /**
   * Predicts developer workload balances
   */
  async predictWorkload(organizationId) {
    const productivities = await analyticsService.getUserProductivity(organizationId);

    const systemInstruction = 'You are the TaskFlow Director of Engineering Resource Allocation.';
    const prompt = `
      Predict the team workload balance using this active developer telemetry:
      ${JSON.stringify(productivities)}

      Synthesize and analyze resource constraints in markdown covering:
      1. Overall workload balance evaluation.
      2. Identification of Overallocated, Optimally Allocated, and Underallocated users.
      3. Actionable strategic resource adjustments recommendations.
    `;

    const aiText = await aiAbstractionLayer.generateText(prompt, systemInstruction);
    if (aiText) return aiText;

    // Premium Local Fallback Workload prediction
    logger.debug('[TaskFlow AI]: Resolving Local Workload Prediction Engine Fallback...');
    
    const overallocated = [];
    const optimal = [];
    const underallocated = [];

    for (const dev of productivities) {
      const activeTasks = dev.totalTasks - dev.completedTasks;
      if (activeTasks > 4) {
        overallocated.push(`- **${dev.name}** (${dev.department || 'Dev'}): tracking **${activeTasks}** active tasks.`);
      } else if (activeTasks >= 2) {
        optimal.push(`- **${dev.name}** (${dev.department || 'Dev'}): tracking **${activeTasks}** active tasks.`);
      } else {
        underallocated.push(`- **${dev.name}** (${dev.department || 'Dev'}): tracking **${activeTasks}** active tasks.`);
      }
    }

    return `### 📊 Resource Workload & Capacity Prediction
*Generated by TaskFlow Resource Allocation AI Engine*

#### 1. Overall Balance Evaluation
The organization's engineering capacity is moderately distributed, with specific silos of extreme allocation that could lead to developer burnout and project delay.

#### 2. Resource Allocation Breakdown

**🚨 Overallocated Developers (Burnout Risk):**
${overallocated.length > 0 ? overallocated.join('\n') : '- None currently detected.'}

**✅ Optimally Allocated Developers (Healthy Flow):**
${optimal.length > 0 ? optimal.join('\n') : '- None currently detected.'}

**💤 Underallocated Developers (Available Capacity):**
${underallocated.length > 0 ? underallocated.join('\n') : '- None currently detected.'}

#### 3. Strategic Resource Adjustments
1. **Distribute Overload**: Reassign minor backlog tasks from overallocated lead engineers to underallocated team members immediately.
2. **Onboard Warm Capacity**: Utilize developers with zero active tasks to assist in review processes.
3. **Cross-Skilling**: Map skills matrices to encourage developers to support adjacent departments during peak phases.
`;
  }

  /**
   * Generates AI text sections for the executive dashboard reports
   */
  async generateAiReportText(organizationId) {
    const kpis = await analyticsService.getKpiDashboard(organizationId);

    const systemInstruction = 'You are the TaskFlow Chief Operations Officer.';
    const prompt = `
      Write an executive operations report segment based on these SaaS workspace KPIs:
      - Active Projects: ${kpis.summary.activeProjects}
      - Active Workspace Users: ${kpis.summary.activeUsers}
      - Task Completion Rate: ${kpis.performance.globalCompletionRate}%
      - Escalated Tasks: ${kpis.summary.escalatedTasks}

      Summarize organizational performance, bottlenecks, and strategic alignment goals in markdown.
    `;

    const aiText = await aiAbstractionLayer.generateText(prompt, systemInstruction);
    if (aiText) return aiText;

    // Premium Local Fallback Executive Report Text
    logger.debug('[TaskFlow AI]: Resolving Local Executive Report Engine Fallback...');
    
    return `### 📈 Executive Performance Operations Report
*Generated by TaskFlow Corporate Strategy AI Engine*

#### 1. Organizational Performance Summary
The enterprise workspace is currently managing **${kpis.summary.activeProjects}** active projects with an active workforce of **${kpis.summary.activeUsers}** developers. The global task completion efficiency is tracking at a stable **${kpis.performance.globalCompletionRate}%**.

#### 2. Operational Bottlenecks & Exposure
- **Escalation Levels**: There are currently **${kpis.summary.escalatedTasks}** CRITICAL tasks that have bypassed standard workflows and require administrative resolution.
- **Resource Constraints**: High concentration of active timelines represents scheduling risk if engineering allocations are not balanced.

#### 3. Strategic Realignment Recommendations
1. **Clear Escalation Backlog**: Prioritize the **${kpis.summary.escalatedTasks}** escalated task blocks in operational standups.
2. **Enhance Velocity Targets**: Aim to improve task completion rates by 5% in the next quarter by enforcing strict work-in-progress (WIP) limits.
3. **Sustain Health Score Boundaries**: Target keeping all project health indexes above 80/100 through weekly automated health telemetry updates.
`;
  }
}

export default new AiService();
